version: '3'

networks:
  3lips:
  adsb-network:
    external: true

services:

  api:
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: 3lips-api
    ports:
      - "${API_PORT:-49156}:5000"
    networks:
      - 3lips
      - adsb-network
    volumes:
      - ./config:/app/config
      - ./common:/app/common
    container_name: 3lips-api
    env_file:
      - .env

  event:
    restart: always
    build:
      context: ./event
      dockerfile: Dockerfile
    image: 3lips-event
    networks:
      - 3lips
      - adsb-network
    volumes:
      - ./config:/app/config
      - ./common:/app/common
      - ./test:/app/test
      - ./save:/app/save
    container_name: 3lips-event
    env_file:
      - .env

  cesium-apache:
    restart: always
    build:
      context: ./cesium
      dockerfile: Dockerfile
    image: cesium-apache
    networks:
      - 3lips
    container_name: 3lips-cesium
    env_file:
      - .env
